### ISSUE TITLE
still pulls in underscore

### ISSUE THREAD

**Issue by macrozone** [aldeed/meteor-collection2#386]
there is still a underscore dependency in .versions, so it will pull in underscore, altough its not used anymore

**Comment by sakulstra** [comment]
@macrozone I'm not sure if .versions files in meteor packages are actually used for anything?

According to meteor list: https://github.com/raix/Meteor-EventEmitter is the culprit here
```
aldeed:collection2@3.0.0                      
├── ecmascript@0.11.1 (top level)             
├─┬ minimongo@1.4.4                           
│ ├─┬ diff-sequence@1.1.0                     
│ │ ├── ecmascript@0.11.1 (top level)         
│ │ └─┬ ejson@1.1.0                           
│ │   ├─┬ base64@1.0.11                       
│ │   │ └── ecmascript@0.11.1 (top level)     
│ │   └── ecmascript@0.11.1 (top level)       
│ ├── ecmascript@0.11.1 (top level)           
│ ├── ejson@1.1.0 (expanded above)            
│ ├─┬ geojson-utils@1.0.10                    
│ │ └─┬ modules@0.12.2                        
│ │   └── modules-runtime@0.10.2              
│ ├─┬ id-map@1.1.0                            
│ │ ├── ecmascript@0.11.1 (top level)         
│ │ └── ejson@1.1.0 (expanded above)          
│ ├─┬ mongo-id@1.0.7                          
│ │ ├── ecmascript@0.11.1 (top level)         
│ │ ├── ejson@1.1.0 (expanded above)          
│ │ ├── id-map@1.1.0 (expanded above)         
│ │ └─┬ random@1.1.0                          
│ │   └── ecmascript@0.11.1 (top level)       
│ ├─┬ ordered-dict@1.1.0                      
│ │ └── ecmascript@0.11.1 (top level)         
│ ├── random@1.1.0 (expanded above)           
│ └── tracker@1.2.0 (top level)               
├── mongo@1.5.1 (top level)                   
├─┬ raix:eventemitter@0.1.3                   
│ └── underscore@1.0.10                       
└─┬ tmeasday:check-npm-versions@0.3.2         
  └── ecmascript@0.11.1 (top level)           
```

**Comment by macrozone** [comment]
this is fixed in raix:eventemitter, but i think @raix  did not yet release a new version

**Comment by macrozone** [comment]
its now released as raix:eventemitter@1.0.0

**Comment by aldeed** [comment]
Published 3.0.2 with `raix:eventemitter@1.0.0` dependency. Run `meteor add raix:eventemitter@1.0.0` or in some other way ensure that the 1.0.0 version ends up in your `.versions` file.

**Comment by Floriferous** [comment]
Even with 3.0.2 and raix:emitter1.0.0 in my .versions file, I still see this package importing an entire copy of underscore. Not sure this is resolved!
